apiVersion: v1
kind: Service
metadata:
  name: shortener-service
  namespace: url-shortener
  labels:
    app: shortener
spec:
  type: ClusterIP
  selector:
    app: shortener
  ports:
    - port: 8000
      targetPort: 8000