---
apiVersion: v1
kind: Secrets
metadata:
  name: db-secret
  namespace: url-shortener
type: opaque
data:
  POSTGRES_PASSWORD: cGFzc3dvcmQ= # base64 encoded value of 'password' 
---
---
apiVersion: apps/v1
kind: Secrets
metadata:
  name: docker-password
  namespace: url-shortener
type: opaque
data:
   dock-pass: TWFub2pAMTIzSw==
---